#!/bin/bash
#
#     Usage: prep dokuwiki repository
#
#     Parameter: -b (specify the basedir in which the conversion starts. subdirs
#                    are searched recursively)
#
#
#     Changelog:
#
# V1.0        by masc
# 2025-04-29: Initial Release
#
#==============================================================================
#
	############################
	# Declaration of functions #
	############################

function printgreen () {
   printf "${GREEN}${1}${NC}"
}

function printred() {
    printf "${RED}${1}${NC}"
}

#
#==============================================================================
#
	#####################
	# Initialize script #
	#####################

# Colours

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color


usage() { echo "Usage: ${0} -b (basedir)" 1>&2; exit 1; }

#
#==============================================================================
#
	############################
	# Declaration of functions #
	############################


#
#==============================================================================
#
	#############
	# main part #
	#############

set -e



exit 0
#
#==============================================================================
